List-2: Benchmark Choices PrintResults Random ReadData Student
	clang++ -std=c++17 -o List-2 Main.cpp Benchmark.o Choices.o PrintResults.o Random.o ReadData.o Student.o
Benchmark:
	clang++ -std=c++17 -c Benchmark.cpp
Choices:
	clang++ -std=c++17 -c Choices.cpp
PrintResults:
	clang++ -std=c++17 -c PrintResults.cpp
Random:
	clang++ -std=c++17 -c Random.cpp
ReadData:
	clang++ -std=c++17 -c ReadData.cpp
Student:
	clang++ -std=c++17 -c Student.cpp
clean:
	rm *.o List-2