Deque: GenerateFile PrintResults Random ReadData Student
	g++ -std=c++17 -o Deque Main.cpp GenerateFile.o PrintResults.o Random.o ReadData.o Student.o
GenerateFile:
	g++ -std=c++17 -c GenerateFile.cpp
PrintResults:
	g++ -std=c++17 -c PrintResults.cpp
Random:
	g++ -std=c++17 -c Random.cpp
ReadData:
	g++ -std=c++17 -c ReadData.cpp
Student:
	g++ -std=c++17 -c Student.cpp
clean:
	rm *.o Deque